language: python

sudo: no

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.6"

script: nosetests --with-coverage --cover-package=flask_emails

before_install:
  - travis_retry pip install coverage coveralls nose pytest mock

install:
  - travis_retry pip install -r requirements.txt

cache:
  directories:
    - $HOME/.pip-cache/

after_success:
  # Report coverage results to coveralls.io
  - coveralls

deploy:
    provider: pypi
    user: lavr
    password:
      secure: "WuFOsmKW77foHa0Ywv7pwXNvSQ+lHSx/IlYxPTuE7dTj1mNgvXC48NXQONY1ZEDiysryimgfsqumvx6PqLsFmOkG4r9k3gaau0eHE063+/hse0YvbqpnzIWa1FTe4yxreJeEHWSiNyAyo0ERaZVMcnj1ii6paHzuMVuCQ/BwV3k="
    on:
      tags: true
      branch: master
    distributions: "sdist bdist_wheel"

